lib/tdl_elixir_web/router.ex
defmodule TdlElixirWeb.Router do
  use TdlElixirWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TdlElixirWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :admin do
    plug TdlElixirWeb.EnsureRolePlug, :admin
  end

  scope "/", TdlElixirWeb do
    pipe_through [:browser, :protected]

    get "/", HomeController, :index
    get "/home/:id", HomeController, :show

    post "/event/ticket/:id", TicketController, :create

    get "/profile", UsersController, :index
    get "/profile/purchases", UsersController, :show
  end

  scope "/admin", TdlElixirWeb do
    pipe_through [:browser, :protected, :admin]

    get "/", EventController, :index
    resources "/event", EventController
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  # Other scopes may use custom stacks.
  # scope "/api", TdlElixirWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TdlElixirWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/tdl_elixir_web/controllers/home_controller.ex
defmodule TdlElixirWeb.HomeController do
  use TdlElixirWeb, :controller
  alias TdlElixir.Event.Event
  alias TdlElixir.Repo
  require Enum

  def show(conn, %{"id" => id}) do
    event = Repo.get!(Event, id)
    render(conn, "show.html", event: event)
  end

  def index(conn, params) do
    events = Event.list_events(params)
    render(conn, "index.html", events: Enum.sort(events))
  end
end

lib/tdl_elixir_web/views/home_view.ex
defmodule TdlElixirWeb.HomeView do
  use TdlElixirWeb, :view
end

lib/tdl_elixir_web/templates/home/index.html.heex
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=2">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <div class="jumbotron">
  <center>
    <h1>Welcome to Boletek </h1>
  </center>
  <center>
    <p> Best web to buy all kind of tickets.</p>
  </center>
  </div>
  <div class="jumbotron"  style="background:#B8B8B8 ">
    <div class="row">
      <div class="col-md-6">
        <center>
          <p>
              <%= link "Profile", to: Routes.users_path(@conn, :index)%>
          </p>
        </center>
      </div>
      <div class="col-md-6">
        <center>
          <p>
            <%= link "Purchases", to: Routes.users_path(@conn, :show) %>
          </p>
        </center>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <%= form_for @conn, Routes.home_path(@conn, :index), [method: :get, name: :search, class: "form-inline"], fn f -> %>
    <div class="form-group col-md-10 " >
      <%= text_input f, :query , placeholder: "Enter event name", class: "control-label" %>
    </div>
    <div class="form-group col-md-2 ">
      <%= submit "Search", class: "btn btn-primary mb-2"%>
    </div>
  <% end %>
</div>

<ul class="list-group">
  <section class="row">
    <%= for event <- @events do %>
      <%# <li class="list-group-item"> %>
        <section class="u-clearfix u-section-1" id="sec-ea0f">
          <div class="u-clearfix u-sheet u-sheet-1">
            <div class="u-expanded-width-lg u-expanded-width-md u-expanded-width-xl u-list u-list-1">
              <div class="u-repeater u-repeater-1">
                <%# <section class="row"> %>
                  <div class="u-container-style u-list-item u-repeater-item u-list-item-1">
                    <div class="u-container-layout u-similar-container u-container-layout-1">
                      <img src="https://picsum.photos/id/158/1200/1500" alt="" class="u-expanded-width u-image u-image-default u-image-1" data-image-width="1200" data-image-height="1500">
                      <h5 class="u-text u-text-default u-text-1"><%= event.name %></h5>
                      <p class="u-text u-text-default u-text-5">
                        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
                        <i class="small material-icons">attach_money</i>
                        Price: <%= event.price%></p>
                      <p class="u-text u-text-default u-text-5">
                        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
                        <i class="small material-icons">event</i>
                        
                        Date: <%= Enum.join [event.date.day, event.date.month, event.date.year] , "/"%></p>
                      <p class="u-text u-text-default u-text-5">
                        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
                        <i class="small material-icons">location_on</i>
                        Location: <%= event.location %></p>
                      <p class="u-text u-text-default u-text-5">
                        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
                        <i class="small material-icons">people</i>
                        Remaining: <%= event.availability %></p>
                      <p class="u-text u-text-default u-text-5">
                      </p>
                      <%= button "Book Now", to: Routes.ticket_path(@conn, :create, event.id), class: "btn btn-primary", style: "text-align:center" %>
                    </div>
                  </div>
                <%# </section> %>
              </div>
            </div>
          </div>
        </section>
      <%# </li> %>
    <% end %>
  </section>
</ul>
</body>